`timescale 1ns / 1ps

// ============================================================================
// Module      : rom_model
// Description : Instruction ROM — 4 KB (1024 × 32-bit words), base 0x0000.
//               Used for simulation only.  The firmware binary is loaded from
//               firmware.mem (generated by build.bat via riscv-none-elf-objcopy).
//
// Read behaviour:
//   - Combinational (asynchronous): output is valid the same cycle the address
//     is presented, matching the I-Cache's expectation.
//   - Address mapping: addr[11:2] selects the word (drops the 2 LSBs that
//     represent the byte offset within a word — RISC-V is always word-aligned
//     for instruction fetches).
//
// Initialisation order:
//   1. Fill every location with NOP (0x00000013 = ADDI x0, x0, 0).
//      This prevents the pipeline from seeing X or 0x00000000 (illegal) on
//      addresses beyond the end of the firmware.
//   2. Load firmware.mem on top.  $readmemh only overwrites the locations
//      present in the file; the rest stay as NOP.
// ============================================================================

module rom_model (
    input  logic [31:0] addr,    // Byte address from CPU / I-Cache
    input  logic        en,      // Chip enable (active high)
    output logic [31:0] rd_data  // 32-bit instruction word output
);

    logic [31:0] mem [0:1023]; // 1024 words = 4 KB

    // -------------------------------------------------------------------------
    // Memory initialisation — runs once at simulation start
    // NOTE: The $readmemh path below is absolute.  If you move the project,
    //       update this path to match your local workspace, or switch to a
    //       relative path (Vivado resolves relative paths from the project root).
    // -------------------------------------------------------------------------
    initial begin
        // Step 1: pre-fill with NOP so unused addresses are safe
        for (int i = 0; i < 1024; i++) begin
            mem[i] = 32'h00000013; // NOP = ADDI x0, x0, 0
        end

        // Step 2: overwrite the first N words with the compiled firmware
        $readmemh("C:/My_Projects/RISCV_SoC_Project/sw/firmware.mem", mem);
    end

    // -------------------------------------------------------------------------
    // Combinational read
    // addr[11:2]  : word index (bits [1:0] are the byte offset, ignored here
    //               because instructions are always 4-byte aligned in RV32I)
    // Returns NOP when chip-enable is deasserted so the pipeline stays clean.
    // -------------------------------------------------------------------------
    assign rd_data = en ? mem[addr[11:2]] : 32'h00000013;

endmodule