`timescale 1ns / 1ps

/**
 * ============================================================================
 * Module      : riscv_core
 * Description : 5-Stage Pipelined RISC-V Core (RV32I).
 * This is the top-level module for the CPU, instantiating all 
 * pipeline stages, intermediate registers, the Hazard Unit, 
 * Forwarding Unit, CSRs, and internal Caches (I-Cache & D-Cache).
 *
 * * Critical Pipeline Interlock Design:
 * To prevent pipeline corruption during multi-cycle cache misses, 
 * all asynchronous pipeline flushes generated by the Hazard Unit 
 * are strictly gated (masked) by the 'dcache_stall' signal. 
 * This ensures that valid instructions pending in the EX/ID stages 
 * are not accidentally erased (flushed) while the global pipeline 
 * is frozen waiting for main memory.
 * ============================================================================
 */
module riscv_core (
    input  logic        clk,
    input  logic        rst_n,

    input  logic        ext_intr,

    // Instruction Memory Interface
    input  logic [31:0] instr_mem_data,
    input  logic        instr_mem_ready,
    output logic [31:0] instr_mem_addr,

    // ROM Interface (Driven by internal I-Cache to the SoC)
    output logic [31:0] rom_addr,
    input  logic [31:0] rom_data,
    output logic        rom_read_en,

    // D-Cache → RAM Interface (driven by internal D-Cache to the SoC)
    output logic [31:0] dcache_ram_addr,
    output logic [31:0] dcache_ram_wr_data,
    output logic        dcache_ram_wr_en,
    output logic        dcache_ram_rd_en,
    input  logic [31:0] dcache_ram_data
);

    // --- 1. Internal Pipeline Wires ---
    logic [31:0] if_pc, if_inst;
    logic        if_pc_en, if_stall;

    logic [31:0] id_pc, id_inst, id_read_data1, id_read_data2, id_imm;
    logic [4:0]  id_rs1, id_rs2, id_rd_addr;
    logic        id_reg_write_en, id_mem_read_en, id_mem_write_en, id_mem_to_reg_sel;
    logic [2:0]  id_alu_op_sel;
    logic        id_alu_src_sel, id_branch_en, id_jal_en, id_jalr_en;
    logic        id_reg_en, if_id_flush, id_rs1_used, id_rs2_used;
    logic [2:0]  id_funct3;
    logic        id_auipc_en, id_csr_en, id_valid_inst;

    logic [31:0] ex_pc, ex_read_data1, ex_read_data2, ex_imm, ex_inst, ex_alu_res, ex_branch_target, ex_wr_data_mem;
    logic [4:0]  ex_rs1, ex_rs2, ex_rd_addr;
    logic        ex_reg_write_en, ex_mem_read_en, ex_mem_write_en, ex_mem_to_reg_sel;
    logic        ex_alu_src_sel, ex_branch_en, ex_alu_zero, ex_jal_en, ex_jalr_en;
    logic [2:0]  ex_alu_op_sel;
    logic        id_ex_flush, ex_rs1_used, ex_rs2_used;
    logic        ex_auipc_en, ex_csr_en, ex_valid_inst;

    // New EX wires for CSR and Interrupts
    logic [31:0] ex_csr_rdata, ex_rs1_fwd_out;
    logic        ex_mret_exec, ex_csr_we;
    logic        take_trap;
    logic [31:0] trap_target, epc_out;
    logic        trap_or_mret_flush;

    logic [31:0] mem_alu_res, mem_wr_data, mem_rd_data, mem_branch_target;
    logic [4:0]  mem_rd_addr;
    logic [2:0]  mem_funct3;
    logic        mem_reg_write_en, mem_mem_read_en, mem_mem_write_en, mem_mem_to_reg_sel;
    logic        mem_branch_en, mem_alu_zero, mem_branch_taken, ex_mem_flush;
    logic        mem_jal_en, mem_jalr_en;
    logic        mem_valid_inst;

    logic [31:0] wb_alu_res, wb_mem_data, wb_final_data;
    logic [4:0]  wb_rd_addr;
    logic        wb_reg_write_en, wb_mem_to_reg_sel, wb_valid_inst;

    logic [1:0]  forward_a_sel, forward_b_sel;
    logic [31:0] final_branch_addr;
    logic        actual_jump;

    // --- UART / Global Stall Wires ---
    logic uart_stall;
    logic uart_wait_cycle_q;
    logic global_stall;

    // --- D-Cache Internal Wires ---
    logic [31:0] dcache_cpu_data;       // Data returned by D-Cache to MEM stage
    logic        dcache_stall;          // Pipeline freeze on D-Cache miss (RAM only)
    logic        dcache_stall_raw;      // Raw stall signal from dcache module
    logic [31:0] formatted_wr_data;     // Formatted store data (byte/half replicated)
    logic [3:0]  data_mem_byte_en;      // Byte-enable from MEM stage (internal only)

    // Intermediate wires for dcache's RAM-bus outputs (before the bypass mux)
    logic [31:0] dcache_ram_addr_int;
    logic [31:0] dcache_ram_wr_data_int;
    logic        dcache_ram_wr_en_int;
    logic        dcache_ram_rd_en_int;

    // MMIO Bypass — do NOT cache accesses outside the RAM window (0x2000–0x2FFF).
    // GPIO (0x1000), UART (0x3000), PIC (0x4000) must reach peripherals immediately.
    logic dcache_bypass;
    assign dcache_bypass = !((mem_alu_res >= 32'h0000_2000) &&
                             (mem_alu_res <= 32'h0000_2FFF));

    // Stall only applies to RAM (cached) accesses
    assign dcache_stall = dcache_stall_raw && !dcache_bypass;

    // Read-data mux: MMIO reads use the raw bus return; RAM reads use dcache output.
    logic [31:0] mem_ram_rd_mux;
    assign mem_ram_rd_mux = dcache_bypass ? dcache_ram_data : dcache_cpu_data;

    // --- Interrupt & Trap Mux Logic ---

    // Detect if the instruction in Execute is an 'mret' (Opcode 1110011, Funct3 000)
    assign ex_mret_exec = (ex_inst[6:0] == 7'b1110011) && (ex_inst[14:12] == 3'b000);

    // We only write to CSR if it's a CSR instruction AND rs1 is not x0 (0)
    assign ex_csr_we = ex_csr_en && (ex_inst[19:15] != 5'b00000);

    // If a trap hits OR an mret is executed, we must flush the front of the pipeline
    assign trap_or_mret_flush = take_trap || ex_mret_exec;

    // The Master PC Multiplexer (Overrides normal jumps if there is a trap/mret)
    logic        final_jump_sel;
    logic [31:0] final_jump_addr;

    always_comb begin
        if (take_trap) begin
            final_jump_sel  = 1'b1;
            final_jump_addr = trap_target; // Jump to ISR
        end else if (ex_mret_exec) begin
            final_jump_sel  = 1'b1;
            final_jump_addr = epc_out;     // Return to saved PC
        end else begin
            final_jump_sel  = actual_jump;
            final_jump_addr = final_branch_addr; // Normal branch/jump
        end
    end

    assign actual_jump = (mem_branch_taken || mem_jal_en || mem_jalr_en);

    // --- Internal I-Cache Wires ---
    logic [31:0] internal_icache_inst;
    logic        icache_stall;

    // ========================================================================
    // Pipeline Stages and Registers Instantiation
    // ========================================================================

    icache u_icache (
        .clk         (clk),
        .rst_n       (rst_n),
        .cpu_pc      (if_pc),
        .cpu_inst    (internal_icache_inst),
        .cpu_stall   (icache_stall),
        .rom_data    (rom_data),
        .rom_pc      (rom_addr),
        .rom_read_en (rom_read_en)
     );

    fetch_stage u_fetch_unit (
        .clk(clk), .rst_n(rst_n), .en(if_pc_en && !global_stall),
        .jump_sel(final_jump_sel), .jump_addr(final_jump_addr),
        .icache_addr(),
        .icache_instr(internal_icache_inst),
        .icache_ready(1'b1),
        .if_pc(if_pc), .if_instr(if_inst), .if_stall(if_stall)
    );

    // [CRITICAL PIPELINE INTERLOCK]: Gating if_id_flush with !dcache_stall
    if_id_reg u_if_id_reg (
        .clk(clk), .rst_n(rst_n), 
        .flush((if_id_flush && !dcache_stall) || trap_or_mret_flush), 
        .en(id_reg_en && !global_stall),
        .if_pc(if_pc), .if_inst(if_inst), .id_pc(id_pc), .id_inst(id_inst)
    );

    decode_stage u_decode_stage (
        .clk(clk), .if_id_inst(id_inst), .if_id_pc(id_pc),
        .wb_reg_write_en(wb_reg_write_en), .wb_write_reg_addr(wb_rd_addr), .wb_write_data(wb_final_data),
        .id_read_data1(id_read_data1), .id_read_data2(id_read_data2), .id_imm(id_imm),
        .id_rs1(id_rs1), .id_rs2(id_rs2), .id_rd(id_rd_addr), .id_funct3(id_funct3),
        .id_reg_write_en(id_reg_write_en), .id_mem_read_en(id_mem_read_en),
        .id_mem_write_en(id_mem_write_en), .id_mem_to_reg_sel(id_mem_to_reg_sel),
        .id_alu_op_sel(id_alu_op_sel), .id_alu_src_sel(id_alu_src_sel),
        .id_branch_en(id_branch_en), .id_jal_en(id_jal_en), .id_jalr_en(id_jalr_en),
        .id_rs1_used(id_rs1_used), .id_rs2_used(id_rs2_used),
        .id_auipc_en(id_auipc_en), .id_csr_en(id_csr_en), .id_valid_inst(id_valid_inst)
    );

    // ========================================================================
    // [CRITICAL PIPELINE INTERLOCK]: Gating Hazard Flushes during Memory Stalls
    // ========================================================================
    // By default, pipeline registers prioritize 'flush' over 'enable' (stall).
    // However, if a multi-cycle memory operation (like a D-Cache miss) stalls 
    // the global pipeline, we MUST prevent the Hazard Unit from flushing 
    // pending instructions that are temporarily frozen.
    //
    // Example Failure (The "Load-Use vs. Cache Miss" Bug):
    // 1. A 'lw' instruction is in EX. A dependent 'addi' is in ID.
    // 2. The Hazard Unit detects a Load-Use hazard and asserts 'id_ex_flush' 
    //    to insert a bubble.
    // 3. Simultaneously, an older instruction in MEM causes a D-Cache miss, 
    //    asserting 'dcache_stall' (which drives 'global_stall').
    // 4. If the flush is ungated, the 'lw' instruction in EX is erased (flushed) 
    //    while the pipeline is frozen, permanently destroying the program state.
    //
    // Fix: Hazard-induced flushes (if_id_flush, id_ex_flush, ex_mem_flush) 
    // are strictly masked by '!dcache_stall'. Trap/MRET flushes remain ungated 
    // because hardware exceptions must override all current pipeline states.
    // ========================================================================
    id_ex_reg u_id_ex_reg (
        .clk(clk), .rst_n(rst_n), 
        .flush((id_ex_flush && !dcache_stall) || trap_or_mret_flush), 
        .en(!global_stall),
        .id_pc(id_pc), .id_read_data1(id_read_data1), .id_read_data2(id_read_data2),
        .id_imm(id_imm), .id_inst(id_inst), .id_rs1(id_rs1), .id_rs2(id_rs2), .id_rd(id_rd_addr),
        .id_alu_op_sel(id_alu_op_sel), .id_alu_src_sel(id_alu_src_sel), .id_reg_write_en(id_reg_write_en),
        .id_mem_read_en(id_mem_read_en), .id_mem_write_en(id_mem_write_en), .id_mem_to_reg_sel(id_mem_to_reg_sel),
        .id_branch_en(id_branch_en), .id_jal_en(id_jal_en), .id_jalr_en(id_jalr_en),
        .id_rs1_used(id_rs1_used), .id_rs2_used(id_rs2_used),
        .id_auipc_en(id_auipc_en), .id_csr_en(id_csr_en), .id_valid_inst(id_valid_inst),
        .ex_pc(ex_pc), .ex_read_data1(ex_read_data1), .ex_read_data2(ex_read_data2),
        .ex_imm(ex_imm), .ex_inst(ex_inst), .ex_rs1(ex_rs1), .ex_rs2(ex_rs2), .ex_rd(ex_rd_addr),
        .ex_alu_op_sel(ex_alu_op_sel), .ex_alu_src_sel(ex_alu_src_sel), .ex_reg_write_en(ex_reg_write_en),
        .ex_mem_read_en(ex_mem_read_en), .ex_mem_write_en(ex_mem_write_en), .ex_mem_to_reg_sel(ex_mem_to_reg_sel),
        .ex_branch_en(ex_branch_en), .ex_jal_en(ex_jal_en), .ex_jalr_en(ex_jalr_en),
        .ex_rs1_used(ex_rs1_used), .ex_rs2_used(ex_rs2_used),
        .ex_auipc_en(ex_auipc_en), .ex_csr_en(ex_csr_en), .ex_valid_inst(ex_valid_inst)
    );

    execute_stage u_execute_stage (
        .ex_pc(ex_pc), .ex_read_data1(ex_read_data1), .ex_read_data2(ex_read_data2),
        .ex_imm(ex_imm), .ex_inst(ex_inst),
        .mem_forward_data(mem_mem_to_reg_sel ? mem_rd_data : mem_alu_res), .wb_forward_data(wb_final_data),
        .forward_a_sel(forward_a_sel), .forward_b_sel(forward_b_sel),
        .ex_alu_op_sel(ex_alu_op_sel), .ex_alu_src_sel(ex_alu_src_sel),
        .ex_branch_en(ex_branch_en), .ex_jal_en(ex_jal_en), .ex_jalr_en(ex_jalr_en),
        .ex_branch_target(ex_branch_target), .ex_alu_result(ex_alu_res),
        .ex_rs1_fwd_out(ex_rs1_fwd_out),
        .ex_write_data_mem(ex_wr_data_mem), .ex_alu_zero(ex_alu_zero),
        .ex_csr_rdata(ex_csr_rdata), .ex_csr_en(ex_csr_en), .ex_auipc_en(ex_auipc_en)
    );

    // [CRITICAL PIPELINE INTERLOCK]: Gating ex_mem_flush with !dcache_stall
    ex_mem_reg u_ex_mem_reg_inst (
        .clk(clk), .rst_n(rst_n),
        .flush((ex_mem_flush && !dcache_stall) || trap_or_mret_flush),
        .en(!global_stall),
        .ex_alu_result(ex_alu_res), .ex_write_data(ex_wr_data_mem), .ex_branch_target(ex_branch_target),
        .ex_rd_addr(ex_rd_addr), .ex_funct3(ex_inst[14:12]), .ex_alu_zero(ex_alu_zero), .ex_valid_inst(ex_valid_inst),
        .ex_reg_write_en(ex_reg_write_en), .ex_mem_to_reg_sel(ex_mem_to_reg_sel),
        .ex_mem_read_en(ex_mem_read_en), .ex_mem_write_en(ex_mem_write_en),
        .ex_branch_en(ex_branch_en), .ex_jal_en(ex_jal_en), .ex_jalr_en(ex_jalr_en),
        .mem_alu_result(mem_alu_res), .mem_write_data(mem_wr_data), .mem_branch_target(mem_branch_target),
        .mem_rd_addr(mem_rd_addr), .mem_funct3(mem_funct3), .mem_alu_zero(mem_alu_zero), .mem_valid_inst(mem_valid_inst),
        .mem_reg_write_en(mem_reg_write_en), .mem_mem_to_reg_sel(mem_mem_to_reg_sel),
        .mem_mem_read_en(mem_mem_read_en), .mem_mem_write_en(mem_mem_write_en),
        .mem_branch_en(mem_branch_en), .mem_jal_en(mem_jal_en), .mem_jalr_en(mem_jalr_en)
    );

    memory_stage u_memory_stage (
        .mem_alu_result(mem_alu_res), .mem_write_data(mem_wr_data),
        .mem_branch_target_in(mem_branch_target),
        .mem_mem_read_en(mem_mem_read_en), .mem_mem_write_en(mem_mem_write_en),
        .mem_branch_en(mem_branch_en), .mem_funct3(mem_funct3), .mem_alu_zero(mem_alu_zero),
        .ram_rd_data(mem_ram_rd_mux),
        .byte_en(data_mem_byte_en),
        .mem_formatted_write_data(formatted_wr_data),
        .mem_read_data(mem_rd_data), .mem_branch_target_out(final_branch_addr),
        .mem_branch_taken(mem_branch_taken)
    );

    dcache u_dcache (
        .clk      (clk),
        .rst_n    (rst_n),
        .cpu_addr (mem_alu_res),
        .wr_data  (formatted_wr_data),
        .we_en    (dcache_bypass ? 1'b0 : mem_mem_write_en),
        .rd_en    (dcache_bypass ? 1'b0 : mem_mem_read_en),
        .byte_en  (data_mem_byte_en),
        .cpu_data  (dcache_cpu_data),
        .cpu_stall (dcache_stall_raw),
        .ram_addr    (dcache_ram_addr_int),
        .ram_wr_data (dcache_ram_wr_data_int),
        .ram_wr_en   (dcache_ram_wr_en_int),
        .ram_rd_en   (dcache_ram_rd_en_int),
        .ram_data    (dcache_ram_data)
    );

    // Bypass mux
    assign dcache_ram_addr    = dcache_bypass ? mem_alu_res       : dcache_ram_addr_int;
    assign dcache_ram_wr_data = dcache_bypass ? formatted_wr_data : dcache_ram_wr_data_int;
    assign dcache_ram_wr_en   = dcache_bypass ? mem_mem_write_en  : dcache_ram_wr_en_int;
    assign dcache_ram_rd_en   = dcache_bypass ? mem_mem_read_en   : dcache_ram_rd_en_int;

    mem_wb_reg u_mem_wb_reg_inst (
        .clk(clk), .rst_n(rst_n),
        .flush(uart_stall && !dcache_stall),
        .en(!dcache_stall),
        .mem_alu_res(mem_alu_res), .mem_mem_data(mem_rd_data), .mem_rd_addr(mem_rd_addr), .mem_valid_inst(mem_valid_inst),
        .mem_reg_write_en(mem_reg_write_en), .mem_mem_to_reg_sel(mem_mem_to_reg_sel),
        .wb_alu_res(wb_alu_res), .wb_mem_data(wb_mem_data), .wb_rd_addr(wb_rd_addr), .wb_valid_inst(wb_valid_inst),
        .wb_reg_write_en(wb_reg_write_en), .wb_mem_to_reg_sel(wb_mem_to_reg_sel)
    );

    writeback_stage u_writeback_stage (
        .wb_alu_res(wb_alu_res), .wb_mem_data(wb_mem_data),
        .wb_mem_to_reg_sel(wb_mem_to_reg_sel), .wb_final_data(wb_final_data)
    );

    forwarding_unit u_forwarding_unit (
        .ex_rs1(ex_rs1), .ex_rs2(ex_rs2), .mem_rd_addr(mem_rd_addr), .wb_rd_addr(wb_rd_addr),
        .mem_reg_write_en(mem_reg_write_en), .wb_reg_write_en(wb_reg_write_en),
        .ex_rs1_used(ex_rs1_used), .ex_rs2_used(ex_rs2_used),
        .forward_a_sel(forward_a_sel), .forward_b_sel(forward_b_sel)
    );

    hazard_detection_unit u_hazard_detection_unit (
        .id_rs1            (id_rs1),
        .id_rs2            (id_rs2),
        .ex_rd_addr        (ex_rd_addr),
        .ex_mem_read_en    (ex_mem_read_en),
        .jump_branch_taken (actual_jump),
        .icache_stall      (icache_stall),
        .mem_mem_read_en   (mem_mem_read_en),
        .mem_alu_result    (mem_alu_res),
        .uart_already_waited (uart_wait_cycle_q),
        .if_pc_en          (if_pc_en),
        .id_reg_en         (id_reg_en),
        .id_ex_flush       (id_ex_flush),
        .if_id_flush       (if_id_flush),
        .ex_mem_flush      (ex_mem_flush),
        .uart_stall        (uart_stall)
    );

    // --- CSR Unit Integration ---
    csr_unit u_csr_unit (
        .clk(clk), .rst_n(rst_n),
        .inst_retired(ex_valid_inst),
        .csr_we(ex_csr_we),
        .csr_addr(ex_inst[31:20]),
        .csr_wdata(ex_rs1_fwd_out),
        .csr_rdata(ex_csr_rdata),
        .current_pc(ex_pc),
        .ext_intr(ext_intr),
        .mret_exec(ex_mret_exec),
        .take_trap(take_trap),
        .trap_target(trap_target),
        .epc_out(epc_out)
    );

    // --- UART Stall Logic ---
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) uart_wait_cycle_q <= 1'b0;
        else        uart_wait_cycle_q <= uart_stall;
    end

    // global_stall: either a UART peripheral wait OR a D-Cache miss
    assign global_stall = uart_stall || dcache_stall;

endmodule